### ISSUE TITLE
Noen forslag til justeringer

### ISSUE THREAD

**Issue by NKAmapper** [osmno/ssr2_to_osm#2]
Ser ut som filene har latt seg generere greit nå. Bare noen detaljer her som kanskje tyder på kluss i koden. Eksemplene er fra Hammerfest:

- Stedsnr 819128, 687008, 202965, og 141010 mangler i filen. De er i WFS, og klarer ikke se noen spesiell årsak til at de ikke skal være med.
- Stedsnr 980822: Her er en ikke-prioritert skrivemåte tatt med i **name**, i stedet for i **alt_name**. Har sett på flere av disse casene, og jeg tror det er bedre å bare ha dem i **alt_name**. Kartverket viser dem ikke i sitt Norgeskart. Se også generelt punkt nedenfor.
- Stedsnr 237775: Her har Statoil Melkøya blitt **alt_name**, men navnestatus er historisk, så bør vel være **old_name**.
- Stedsnr 574811: Her har Porsangerhalvøya fått **name:no**, selv det ikke er andre språk for dette stedet. Bør vel bare være **name**.
- Stedsnr 566027: Her har Rypefjellet og Rypfjellet kommet med som samiske navn, men de står som norske i wfs'en (og er ikke prioriterte skrivemåter, så bør ikke være i **name**).
- Stedsnr 505833: Her er "Okselva, øvre" tatt med i **name**. Den er sidenavn, men er ikke prioritert. Bør være i **alt_name**.

Og tre generelle forslag til endringer:

- Ikke "oppgradere" ikke-prioriterte skrivemåter til **name** når det mangler et hovednavn. Bare ta med i **alt_name**. Har gått igjennom en del caser, og vi vil bare "miste" navn som allerede er inne via andre stedsnr, eller der det er reist navnesak. Det siste eksemplet ovenfor viser også at det ellers kan bli kluss med prioriteringen der det finnes flere alternativer.
- Ikke ta med "**:no**" for samtlige norske navn i kommuner som er en del av samisk forvaltningsområde (der stedsnummeret ikke har andre språk). Antallet kommuner har økt de siste år årene, f.eks. er Røros også med nå. Men det er svært få samiske/kvenske navn i mange av disse kommunene, typisk under 10-15%, mens f.eks. Hammerfest har over 1000 samiske navn (38%), men ligger utenfor samisk forvaltningsområde, og dermed ikke har regelen om "**:no**" for alle navn. Tror en slik endring blir mer konsistent på tvers av kommunegrenser, og greit forståelig også der det er mange samiske navn. Greit å fortsette med "**:no**" for stedsnummer der det også finnes andre språk.
- Skrive ekstra tags med store bokstaver (TYPE, GRUPPE, HOVEDGRUPPE, DATO). Da er de lettere å huske, det blir gitt feilmeldinger i JOSM og de blir plukket opp av globale bots dersom de lastes opp.

Ellers: Jeg skal holde taggefilen https://github.com/NKAmapper/ssr2osm/blob/main/navnetyper_tagged.json oppdatert fremover, så du kan vurdere å bruke den direkte. Den vil bli brukt også av andre programmer, bl.a. n50osm og geocode2osm, så da kan filene brukes konsistent på tvers. Er gjort et par oppdateringer siste dagene.

**Comment by obtitus** [comment]
> Stedsnr 819128, 687008, 202965, og 141010 mangler i filen. De er i WFS, og klarer ikke se noen spesiell årsak til at de ikke skal være med.

fra loggen, som desverre er for stor til å laste opp som default:
utility_to_osm - INFO - ssr:stedsnr = 819128 not active = "relikt". Skipping..
utility_to_osm - INFO - ssr:stedsnr = 687008 not active = "relikt". Skipping...
utility_to_osm - INFO - ssr:stedsnr = 202965 not active = "relikt". Skipping...
utility_to_osm - INFO - ssr:stedsnr = 141010 not active = "relikt". Skipping...
Disse feiler sjekk om stedstatus == 'aktiv', mener du at de skal med?

**Comment by NKAmapper** [comment]
Aha, jeg hadde ikke sett at de sto som relikt. Litt usikker på hvordan disse behandles. "Objektet eksisterer ikke lengre, men stedsnavnet kan fortsatt være i bruk." Ett av disse fire navnene vises på Norgeskart, mens de tre andre ikke vises. Alle fire er med i de forenklede filene som "godkjente" navn, og de er merket som prioritert. La dem ligge, så kan jeg heller høre hos Kartverket.

**Comment by obtitus** [comment]
> Stedsnr 980822: Her er en ikke-prioritert skrivemåte tatt med i name, i stedet for i alt_name.
> Ikke "oppgradere" ikke-prioriterte skrivemåter til name når det mangler et hovednavn

Skrudde av denne koden. 980822 er ikke lengre med.

> Stedsnr 237775: Her har Statoil Melkøya blitt alt_name

Hmm, denne koden sjekket for skrivemåtestatus, som her var privat. La til en sjekk om navnestatus er "historisk". Fikser 237775.

> Ikke ta med ":no" for samtlige norske navn i kommuner som er en del av samisk forvaltningsområde (der stedsnummeret ikke har andre språk).

Fjernet denne sjekken. 574811 er nå fikset.

Har lastet opp en ny 5406.

**Comment by NKAmapper** [comment]
Nå forsvant det et stort antall samiske navn fra name=* der de før sto sammen med et norsk navn, dvs. med bindestrek. For eksempel 980826. Og et stort antall stedsnavn kom ikke med i det hele tatt, f.eks. 141171.

**Comment by obtitus** [comment]
>> Stedsnr 980822: Her er en ikke-prioritert skrivemåte tatt med i name, i stedet for i alt_name.
>>> Ikke "oppgradere" ikke-prioriterte skrivemåter til name når det mangler et hovednavn

>> Skrudde av denne koden. 980822 er ikke lengre med.

> Og et stort antall stedsnavn kom ikke med i det hele tatt, f.eks. 141171.

Det er denne koden som "oppgraderer" alt_name til navn. 141171 har ikke noe prioritertSkrivemåte, fra loggen:
utility_to_osm - INFO - ssr:stedsnr = 141171: No priority spelling found for lang = no, using alt_name to get "[('no', 'Bastafjorden')]"
så når jeg skrudde av denne oppgraderingen forsvant både 980822 og f.eks. 141171. Reverted denne endringen. Log vedlagt: 
[5406.log](https://github.com/osmno/ssr2_to_osm/files/7921029/5406.log).
Har lastet opp en ny 5406.

**Comment by NKAmapper** [comment]
Du har rett mht. prioritert skrivemåte, men det rimer ikke med hvordan Kartverket viser stedsnavnet: https://stadnamn.kartverket.no/fakta/141171. Jeg får spørre Karterket om disse i morgen.
Har du mulighet til å generere fil for Grimstad også?

**Comment by obtitus** [comment]
> Ikke "oppgradere" ikke-prioriterte skrivemåter til name når det mangler et hovednavn.

Skrudde av denne koden. Merk at jeg ikke genererer noder når name mangler. For osm ser jeg ikke helt poenget med en node som ikke har name, men har alt_name.

> Stedsnr 237775: Her har Statoil Melkøya blitt alt_name, men navnestatus er historisk, så bør vel være old_name.

Ser det er forskjell på navnesakstatus og skrivemåtestatus, tror jeg har fikset historisk i hvert fall.

> Stedsnr 574811: Her har Porsangerhalvøya fått name:no
> Ikke ta med ":no" for samtlige norske navn i kommuner som er en del av samisk forvaltningsområde

Det var en sjekk her om norsk var prioritert skrivemåte, har fjernet.

Gjenstår
> Stedsnr 566027: Her har Rypefjellet og Rypfjellet kommet med som samiske navn, men de står som norske i wfs'en (og er ikke prioriterte skrivemåter, så bør ikke være i name).
> Stedsnr 505833: Her er "Okselva, øvre" tatt med i name. Den er sidenavn, men er ikke prioritert. Bør være i alt_name.
> Ellers: Jeg skal holde taggefilen https://github.com/NKAmapper/ssr2osm/blob/main/navnetyper_tagged.json oppdatert fremover

**Comment by NKAmapper** [comment]
Enig i at det ikke skal genereres  node om name mangler.

Fant en til: 505247 - https://stadnamn.kartverket.no/fakta/505247:
Her er Torskefjordfjellet ikke prioritert, og en annen skrivemåte er prioritert (Torskefjellet) og er sidenavn, likevel har Torskefjordfjellet kommet med i name. Sidenavn har samme rang som Hovednavn - kan komme direkte i name. Her er det ett samisk hovednavn og to norske sidenavn, alle med samme rang.

**Comment by obtitus** [comment]
> Fant en til: 505247 -

Tja, tror jeg fikset denne nå, diff:

```
Diff 89890, alt_name:no missing in new:
 old[alt_name:no] = Raudojormen

Diff 89890, fixme missing in old:
 new[fixme] = multiple name tags, choose one and add the other to alt_name

Diff 89890:
 old[name:no] = Hauankulpen;Raudojormen
 new[name:no] = Hauankulpen

Diff 89890:
 old[name] = Hauankulpen;Raudojormen - Rávdojorbmi
 new[name] = Hauankulpen - Rávdojorbmi

Diff 505247, alt_name:no missing in new:
 old[alt_name:no] = Torskefjordfjellet

Diff 505247:
 old[name:no] = Torskefjellet;Kollfjellet;Torskefjordfjellet
 new[name:no] = Torskefjellet;Kollfjellet

Diff 505247:
 old[name] = Torskefjellet;Kollfjellet;Torskefjordfjellet - Govččá
 new[name] = Torskefjellet;Kollfjellet - Govččá

Diff 505833, alt_name:no missing in new:
 old[alt_name:no] = Okselva, øvre

Diff 505833:
 old[name:no] = Okselva;Okselva, øvre;Øvre Okselva
 new[name:no] = Okselva;Øvre Okselva

Diff 505833:
 old[name] = Okselva;Okselva, øvre;Øvre Okselva - Vuoksajohka
 new[name] = Okselva;Øvre Okselva - Vuoksajohka
```

**Comment by NKAmapper** [comment]
Jeg fikk svar fra Kartverket nå vedr. 141171 (Bastafjorden) ovenfor. Det ser ut til at vi skal ta med alle "vedtatt" i name:xx=* (og name=*) selv om de ikke er merket som prioritert:

> Her er det vedtatt skrivemåte, det er aldri prioritert mellom vedtatte. Dersom det er en eller flere (skjelden) vedtatte skrivemåter så skal disse brukes i offentlig sammenheng.

Med dette kan vi unngå helt å "forfremme" alt_name=* til name=*, mener jeg. Kan sjekke neste kjøring.

Gjelder også f.eks. 383121 (Tubåfallet) i Hammerfest.

Ellers: Et annet av spørsmålene ledet til at de fant 1300 navn som ikke var merket med prioritering, f.eks. 971054 i Grimstad. Disse blir rettet fremover, men det tar litt tid. Får bare kjøre en ny oppdatering om en stund.

**Comment by obtitus** [comment]
> Gjelder også f.eks. 383121 (Tubåfallet) i Hammerfest.

Så her vil vi ha name=Tubåfallet;Tubåen ?

Lastet opp ny 5406, med oppdatert fra kartverket. og 
```python
if status == u'vedtatt':
    priority_spelling = True
```

**Comment by NKAmapper** [comment]
Ja, både Tubåfallet og Tubåen skal med i name=*.

Kjøringen ser riktig ut nå. Eneste avviket jeg fant er 980822 Sørelven. Her er prioritert skrivemåte false, og da skal den ikke med i name=*, og kommer da heller ikke med i filen (ingen alt_name=* skal løftes til name=* etter siste endring for "vedtatt").

Noen av de andre forslagene øverst er kanskje ikke vurdert ennå.

11 navn deles med andre kommuner, og noen av dem langt utenfor kommunegrensen, f.eks. 1075695 Ishavsbyen vgs i Tromsø, 201895 Rognsundet og 80188 Sørøysundet. De er også med i nabokommunenes filer. En mulighet er å bare ta med navn der første kommunenummer i WFS'en stemmer, men da mister man f.eks. 81432 Hamnefjorddalen fra Hammerfest-filen (den kommer med for Hasvik). I forenklet-filene er det brukt en annen inndeling mellom kommunen, men usikker på hvordan. Ikke så viktig kanskje.

**Comment by obtitus** [comment]
> Kjøringen ser riktig ut nå. Eneste avviket jeg fant er 980822 Sørelven. Her er prioritert skrivemåte false, og da skal den ikke med i name=, og kommer da heller ikke med i filen (ingen alt_name= skal løftes til name=* etter siste endring for "vedtatt").

Skrudde av upgrade_alt_names_to_names, dette fjernet 980822

```
git diff 5406.osm
INFO:utility_to_osm.ssr2.git_diff:Reading data/5406/5406.osm
INFO:utility_to_osm.ssr2.git_diff:Reading /tmp/E31Dma_5406.osm

=== Missing stedsnr ===

Diff, 980822 missing in new
<node lat="70.52910104495678" lon="23.392502895705984" id="-102421">
        <tag k="name" v="Sørelven" />
        <tag k="place" v="farm" />
        <tag k="ssr:date" v="2019-12-27" />
        <tag k="ssr:gruppe" v="gardsbebyggelse" />
        <tag k="ssr:hovedgruppe" v="bebyggelse" />
        <tag k="ssr:stedsnr" v="980822" />
        <tag k="ssr:type" v="bruk" />
</node>


=== Tagging differences ===
```

> 11 navn deles med andre kommuner, og noen av dem langt utenfor kommunegrensen,

Tror jeg ignorerer denne, man må uansett passe på og ikke importere duplikater.

**Comment by NKAmapper** [comment]
Husk å oppdatere taggetabell, eller bruke den nye json-linken. :)
